spring:
  rsocket:
    server:
      mapping-path: /rsocket
      transport: websocket
  application:
    name: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
logging:
  level:
    reactor: debug
    io.rsocket: debug
