spring:
  rsocket:
    server:
      port: 7000
  application:
    name: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
logging:
  level:
    reactor: debug
    io.rsocket: debug
