services:
  postgresql:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: balamut
      POSTGRES_PASSWORD: maks
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped
  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
      - "9042:9042"
    networks:
      - microservices-net
    environment:
      - CASSANDRA_USER=root
      - CASSANDRA_PASSWORD=password
    restart: unless-stopped
networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
