spring:
  application:
    name: contacts-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/contacts
    username: balamut
    password: maks
  flyway:
    user: balamut
    password: maks
    url: jdbc:postgresql://localhost:5432/contacts
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/
  cloud:
    loadbalancer:
      enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081
