spring:
  application:
    name: message-service
  cassandra:
    contact-points: localhost:9042
    keyspace-name: messages
    password: password
    username: user
    local-datacenter: datacenter1
    schema-action: recreate_drop_unused
