name: Deploying chat service
on:
  push:
    paths:
      - 'services/chat/**'
jobs:
  testing-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            services/chat/*.gradle*
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
        working-directory: services/chat
      - name: Test with Gradle
        working-directory: services/chat
        run: ./gradlew test
  read-version:
    needs: testing-project
    environment: xemii16
    runs-on: ubuntu-latest
    steps:
      - name: Checkout YeChat repository
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: | # optional
            services/chat/*.gradle*
            services/chat/**/gradle-wrapper.properties
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
        working-directory: services/chat
      - name: Read ChatService version
        working-directory: services/chat
        run: echo "VERSION_NAME=$( ./gradlew -q getVersionName )" >> $GITHUB_ENV
      - name: Build ChatService
        working-directory: services/chat
        run: ./gradlew bootJar --no-daemon
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_EMAIL }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t xemii16/yechat-chat:latest -t xemii16/yechat-chat:${{ env.VERSION_NAME }} services/chat
      - name: Push Docker image
        run: docker push xemii16/yechat-chat:${{ env.VERSION_NAME }}

